USE `bdapp_metro`;

--
-- Estructura para la vista `vw_herramientas_ocupadas`
--
DROP VIEW IF EXISTS `vw_herramientas_ocupadas`;
DROP TABLE IF EXISTS `vw_herramientas_ocupadas`;

CREATE ALGORITHM=UNDEFINED DEFINER=CURRENT_USER SQL SECURITY INVOKER VIEW `vw_herramientas_ocupadas`  AS SELECT `hot`.`id_ai_herramientaOT` AS `id_ai_herramientaOT`, `hot`.`id_ai_herramienta` AS `id_ai_herramienta`, `h`.`nombre_herramienta` AS `nombre_herramienta`, `hot`.`n_ot` AS `n_ot`, `ot`.`nombre_trab` AS `nombre_trab`, `hot`.`cantidadot` AS `cantidadot`, coalesce(`eo`.`nombre_estado`,'SIN ESTADO') AS `estado_ot`, coalesce(`det`.`id_user_act`,`ot`.`id_user`,'') AS `tecnico_id`, coalesce(`emp_det`.`nombre_empleado`,`emp_ot`.`nombre_empleado`,'Sin tecnico asignado') AS `tecnico_nombre`, coalesce(`emp_det`.`telefono`,`emp_ot`.`telefono`,'') AS `telefono`, coalesce(`emp_det`.`correo`,`emp_ot`.`correo`,'') AS `correo`, coalesce(`emp_det`.`direccion`,`emp_ot`.`direccion`,'') AS `direccion`, `hot`.`estado_herramientaot` AS `estado_herramientaot`, `ot`.`fecha` AS `fecha_ot` FROM ((((((`herramientaot` `hot` join `herramienta` `h` on(`h`.`id_ai_herramienta` = `hot`.`id_ai_herramienta` and `h`.`std_reg` = 1)) join `orden_trabajo` `ot` on(`ot`.`n_ot` = `hot`.`n_ot` and `ot`.`std_reg` = 1)) left join `estado_ot` `eo` on(`eo`.`id_ai_estado` = `ot`.`id_ai_estado`)) left join (select `d1`.`n_ot` AS `n_ot`,`d1`.`id_user_act` AS `id_user_act` from (`detalle_orden` `d1` join (select `detalle_orden`.`n_ot` AS `n_ot`,max(`detalle_orden`.`id_ai_detalle`) AS `max_id` from `detalle_orden` group by `detalle_orden`.`n_ot`) `d2` on(`d2`.`n_ot` = `d1`.`n_ot` and `d2`.`max_id` = `d1`.`id_ai_detalle`))) `det` on(`det`.`n_ot` = `hot`.`n_ot`)) left join `empleado` `emp_det` on(`emp_det`.`id_empleado` = `det`.`id_user_act` and `emp_det`.`std_reg` = 1)) left join `empleado` `emp_ot` on(`emp_ot`.`id_empleado` = `ot`.`id_user` and `emp_ot`.`std_reg` = 1)) WHERE coalesce(`hot`.`estado_herramientaot`,'ASIGNADA') <> 'LIBERADA' ;
