USE `bdapp_metro`;

--
-- Estructura para la vista `vw_ot_resumen`
--
DROP VIEW IF EXISTS `vw_ot_resumen`;
DROP TABLE IF EXISTS `vw_ot_resumen`;

CREATE ALGORITHM=UNDEFINED DEFINER=CURRENT_USER SQL SECURITY INVOKER VIEW `vw_ot_resumen`  AS SELECT `ot`.`id_ai_ot` AS `id_ai_ot`, `ot`.`n_ot` AS `n_ot`, `ot`.`fecha` AS `fecha`, `ot`.`semana` AS `semana`, `ot`.`mes` AS `mes`, `ot`.`nombre_trab` AS `nombre_trab`, `ot`.`id_ai_area` AS `id_ai_area`, `area`.`nombre_area` AS `nombre_area`, `area`.`nomeclatura` AS `area_nomeclatura`, `ot`.`id_ai_sitio` AS `id_ai_sitio`, `sitio`.`nombre_sitio` AS `nombre_sitio`, `ot`.`id_ai_estado` AS `id_ai_estado`, `eo`.`nombre_estado` AS `nombre_estado`, `eo`.`color` AS `color_estado`, coalesce(`eo`.`libera_herramientas`,0) AS `libera_herramientas`, coalesce(`eo`.`bloquea_ot`,0) AS `bloquea_ot`, coalesce(`ot`.`ot_finalizada`,0) AS `ot_finalizada`, `ot`.`fecha_finalizacion` AS `fecha_finalizacion`, `ot`.`id_user_finaliza` AS `id_user_finaliza`, `ot`.`id_user` AS `id_user_responsable`, `us`.`username` AS `username_responsable`, `emp`.`nombre_empleado` AS `empleado_responsable`, `emp`.`telefono` AS `telefono_responsable`, `emp`.`correo` AS `correo_responsable`, coalesce(`det`.`total_detalles`,0) AS `total_detalles`, coalesce(`hot`.`herramientas_asignadas`,0) AS `herramientas_asignadas`, coalesce(`hot`.`herramientas_activas`,0) AS `herramientas_activas`, `ot`.`std_reg` AS `std_reg` FROM (((((((`orden_trabajo` `ot` left join `area_trabajo` `area` on(`area`.`id_ai_area` = `ot`.`id_ai_area`)) left join `sitio_trabajo` `sitio` on(`sitio`.`id_ai_sitio` = `ot`.`id_ai_sitio`)) left join `estado_ot` `eo` on(`eo`.`id_ai_estado` = `ot`.`id_ai_estado`)) left join `user_system` `us` on(`us`.`id_empleado` = `ot`.`id_user`)) left join `empleado` `emp` on(`emp`.`id_empleado` = `ot`.`id_user`)) left join (select `detalle_orden`.`n_ot` AS `n_ot`,count(0) AS `total_detalles` from `detalle_orden` group by `detalle_orden`.`n_ot`) `det` on(`det`.`n_ot` = `ot`.`n_ot`)) left join (select `herramientaot`.`n_ot` AS `n_ot`,coalesce(sum(`herramientaot`.`cantidadot`),0) AS `herramientas_asignadas`,coalesce(sum(case when coalesce(`herramientaot`.`estadoot`,'ASIGNADA') <> 'LIBERADA' then `herramientaot`.`cantidadot` else 0 end),0) AS `herramientas_activas` from `herramientaot` group by `herramientaot`.`n_ot`) `hot` on(`hot`.`n_ot` = `ot`.`n_ot`)) WHERE `ot`.`std_reg` = 1 ;
