USE `bdapp_metro`;

--
-- Estructura para la vista `vw_ot_detallada`
--
DROP VIEW IF EXISTS `vw_ot_detallada`;
DROP TABLE IF EXISTS `vw_ot_detallada`;

CREATE ALGORITHM=UNDEFINED DEFINER=CURRENT_USER SQL SECURITY INVOKER VIEW `vw_ot_detallada`  AS SELECT `det`.`id_ai_detalle` AS `id_ai_detalle`, `det`.`n_ot` AS `n_ot`, `ot`.`id_ai_ot` AS `id_ai_ot`, `ot`.`fecha` AS `fecha_ot`, `ot`.`nombre_trab` AS `nombre_trab`, `ot`.`semana` AS `semana`, `ot`.`mes` AS `mes`, `ot`.`id_ai_area` AS `id_ai_area`, `area`.`nombre_area` AS `nombre_area`, `area`.`nomeclatura` AS `area_nomeclatura`, `ot`.`id_ai_sitio` AS `id_ai_sitio`, `sitio`.`nombre_sitio` AS `nombre_sitio`, `ot`.`id_ai_estado` AS `id_ai_estado`, `eo`.`nombre_estado` AS `estado_ot`, `eo`.`color` AS `color_estado_ot`, coalesce(`eo`.`libera_herramientas`,0) AS `libera_herramientas`, coalesce(`eo`.`bloquea_ot`,0) AS `bloquea_ot`, `det`.`fecha` AS `fecha_detalle`, `det`.`descripcion` AS `descripcion`, `det`.`id_ai_turno` AS `id_ai_turno`, `tt`.`nombre_turno` AS `nombre_turno`, `det`.`id_user_act` AS `id_user_act`, `us_det`.`username` AS `username_usuario_act`, `emp_det`.`nombre_empleado` AS `usuario_act_nombre`, `det`.`id_miembro_cco` AS `id_miembro_cco`, `mcco`.`nombre_miembro` AS `miembro_cco_nombre`, `det`.`id_miembro_ccf` AS `id_miembro_ccf`, `mccf`.`nombre_miembro` AS `miembro_ccf_nombre`, `det`.`cant_tec` AS `cant_tec`, `det`.`hora_inicio` AS `hora_inicio`, `det`.`hora_fin` AS `hora_fin`, `det`.`observacion` AS `observacion`, coalesce(`ot`.`ot_finalizada`,0) AS `ot_finalizada` FROM (((((((((`detalle_orden` `det` join `orden_trabajo` `ot` on(`ot`.`n_ot` = `det`.`n_ot` and `ot`.`std_reg` = 1)) left join `area_trabajo` `area` on(`area`.`id_ai_area` = `ot`.`id_ai_area`)) left join `sitio_trabajo` `sitio` on(`sitio`.`id_ai_sitio` = `ot`.`id_ai_sitio`)) left join `estado_ot` `eo` on(`eo`.`id_ai_estado` = `ot`.`id_ai_estado`)) left join `turno_trabajo` `tt` on(`tt`.`id_ai_turno` = `det`.`id_ai_turno`)) left join `user_system` `us_det` on(`us_det`.`id_empleado` = `det`.`id_user_act`)) left join `empleado` `emp_det` on(`emp_det`.`id_empleado` = `det`.`id_user_act`)) left join `miembro` `mcco` on(`mcco`.`id_miembro` = `det`.`id_miembro_cco`)) left join `miembro` `mccf` on(`mccf`.`id_miembro` = `det`.`id_miembro_ccf`)) ;
